# Generated by Django 4.0.3 on 2022-04-11 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_productcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='estimation',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
